SELECT * FROM cwiczeniesda1.pracownicysda;
use cwiczeniesda1;
drop table pracownicysda;
Create table wyksztalcenie (
id INT PRIMARY KEY,
nazwa TEXT
);
INSERT INTO wyksztalcenie(id, nazwa) values (1, 'WYZSZE');
INSERT INTO wyksztalcenie(id, nazwa) values (2, 'SREDNIE');
INSERT INTO wyksztalcenie(id, nazwa) values (3, 'PODSTAWOWE');
show tables;

create table departament (
id int primary key,
nazwa varchar(255)
);
insert into departament values (1, 'IT');
insert into departament values (2, 'QA');
insert into departament values (3, 'FINANCE');
show TABLES

CREATE TABLE PRACOWNICY (
ID BIGINT AUTO_INCREMENT PRIMARY KEY,
IMIE VARCHAR(255),
NAZWISKO VARCHAR(255),
WYNAGRODZENIE NUMERIC(15, 2),
ID_DEPARTAMENT int REFERENCES DEPARTAMENT(ID),
ID_WYKSZTAŁCENIE INT REFERENCES WYKSZTALCENIE(ID)
);
INSERT INTO PRACOWNICY 
(IMIE, NAZWISKO, WYNAGRODZENIE, ID_DEPARTAMENT, ID_WYKSZTAŁCENIE) 
VALUES ('TOMASZ', 'LIS', 1500.00, 1, 2);
INSERT INTO PRACOWNICY 
(IMIE, NAZWISKO, WYNAGRODZENIE, ID_DEPARTAMENT, ID_WYKSZTAŁCENIE) 
VALUES ('JOANNA', 'MIAST', 500.00, 2, 2);
INSERT INTO PRACOWNICY 
(IMIE, NAZWISKO, WYNAGRODZENIE, ID_DEPARTAMENT, ID_WYKSZTAŁCENIE) 
VALUES ('KASIA', 'KOWALSKA', 30000.00, 1, 2);
INSERT INTO PRACOWNICY 
(IMIE, NAZWISKO, WYNAGRODZENIE, ID_DEPARTAMENT, ID_WYKSZTAŁCENIE) 
VALUES ('OLA', 'DUL', 10000.00, 1, 3);
SELECT * FROM PRACOWNICY;

CREATE TABLE ADRES (
ID BIGINT AUTO_INCREMENT PRIMARY KEY,
MIEJSCOWOSC VARCHAR(255),
ULICA VARCHAR(255),
NR_DOMU VARCHAR(255)
);
INSERT INTO ADRES 
VALUES (DEFAULT, 'WROCLAW', 'OBORNICKA', 1);
INSERT INTO ADRES 
VALUES (DEFAULT, 'WROCLAW', 'KROLEWIECKA', 12);
INSERT INTO ADRES 
VALUES (DEFAULT, 'LUBIN', 'STARA', 234);

ALTER TABLE PRACOWNICY ADD COLUMN ID_ADRES INT references ADRES(ID);
UPDATE PRACOWNICY SET ID_ADRES = 1 WHERE ID< 4;
update PRACOWNICY SET ID_ADRES = 2 WHERE ID>= 4;

SELECT P.IMIE, P.NAZWISKO, ULICA, P.WYNAGRODZENIE
FROM PRACOWNICY P JOIN ADRES A 
ON (A.ID = P.ID_ADRES)
ORDER BY P.WYNAGRODZENIE DESC
LIMIT 5;

SELECT IMIE FROM PRACOWNICY WHERE IMIE LIKE 'J%' AND WYNAGRODZENIE > 500;
SELECT IMIE FROM PRACOWNICY JOIN ADRES A ON (A.ID = ID_ADRES)

SELECT IMIE, NAZWISKO, WYNAGRODZENIE
FROM PRACOWNICY 
WHERE WYNAGRODZENIE BETWEEN 1500 AND 3000
ORDER BY 3 DESC, 2, 1;

SELECT IMIE, NAZWISKO FROM PRACOWNICY
WHERE IMIE = 'OLA' OR NOT NAZWISKO LIKE 'K%';
SELECT IMIE, NAZWISKO FROM PRACOWNICY
WHERE IMIE = 'OLA' AND NOT NAZWISKO LIKE 'K%';